Repository datwit/landing3, pull requests merged in 2022-11, with the labels that each got.

#225 fix(pages): tags should be a list
  _content/studycases/flalq.md
  _content/studycases/landing2.md
  _content/studycases/landing3.md
  _content/studycases/preprocess.md
  cache/cases.json
  cache/posts.json
  components/Home/StudyCases/StudyCasesCard.js
  components/Home/StudyCases/style.js
  pages/studycases/index.js
  pages/studycases/search.js
  scripts/cache.js
Labels: bug, feature

#227 Development
  _content/studycases/flalq.md
  _content/studycases/landing2.md
  _content/studycases/landing3.md
  _content/studycases/preprocess.md
  cache/cases.json
  cache/posts.json
  components/Home/StudyCases/StudyCasesCard.js
  components/Home/StudyCases/style.js
  pages/studycases/index.js
  pages/studycases/search.js
  scripts/cache.js
Labels: bug

#230 fix: :zap: Fix dependencies errors and warnings
  package-lock.json
  package.json
  pages/blog/[slug].js
  pages/info/[slug].js
  pages/studycases/[slug].js
Labels: bug, pack / deployment

#231 updating team members
  components/AboutUs/Collaborators/collaborators.json
  components/AboutUs/Founders/founders.json
  components/AboutUs/Members/team.json
  pages/about/index.js
Labels: doc / content

#233 fix: :art: Fix markdown errors
  _content/studycases/flalq.md
  _content/studycases/landing3.md
Labels: bug

#235 Bastion fix
  _content/studycases/bastion_host.md
  components/AboutUs/Collaborators/collaborators.json
  public/members/v2/denys.jpeg
Labels: bug

#236 content: adding collaborator Denys
  components/AboutUs/Collaborators/collaborators.json
Labels: bug, doc / content

#237 content: adding collaborator Denys
  _content/studycases/bastion_host.md
  components/AboutUs/Collaborators/collaborators.json
  public/members/v2/denys.jpeg
Labels: bug, doc / content

#238 Update collaborators.json
  components/AboutUs/Collaborators/collaborators.json
Labels: doc / content
